actx_meter_enabled=true
hook_service_patterns=com.sun.net.httpserver.HttpHandler.handle
httpc_host_meter_enabled=true
logsink_enabled=true
logsink_trace_enabled=true
mtrace_enabled=true
mtrace_rate=100
profile_basetime=1
sql_dbc_meter_enabled=true
trace_ignore_url_set=/api/test2
tx_caller_meter_enabled=true

license=x20ggf3ermhon-x3svveb1btoid4-x2vlt4dmk86f49
whatap.server.host=172.26.71.228
